# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-22 04:21
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0002_auto_20181121_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='answer',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
