# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-22 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0004_player_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='question_id',
        ),
    ]
