# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-22 04:29
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0006_player_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='game_id',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
