# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-23 01:18
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0008_auto_20181122_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='seat_number',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Your Seat Number:'),
        ),
    ]
