# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-23 01:19
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0009_player_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=otree.db.models.StringField(choices=[('18-19', '18-19'), ('20-21', '20-21'), ('22-23', '22-23'), ('24-25', '24-25'), ('26 and older', '26 and older')], max_length=10000, null=True, verbose_name='How old are you'),
        ),
        migrations.AddField(
            model_name='player',
            name='experience',
            field=otree.db.models.StringField(choices=[('very much', 'very much'), ('to a great degree', 'to a great degree'), ('in some  ocassions', 'in some  ocassions'), ('rarely or not at all', 'rarely or not at all')], max_length=10000, null=True, verbose_name='Do you practice “word puzzles” and “number puzzles” as a hobby,'),
        ),
        migrations.AddField(
            model_name='player',
            name='gender',
            field=otree.db.models.StringField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10000, null=True, verbose_name='What is your gender?'),
        ),
    ]
