# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-25 01:35
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0010_auto_20181123_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='player',
            name='game_attempt',
        ),
        migrations.RemoveField(
            model_name='player',
            name='game_correct',
        ),
        migrations.RemoveField(
            model_name='player',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='question_id',
        ),
        migrations.AddField(
            model_name='player',
            name='game_attemptted',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='game_correctted',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
