# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-25 02:43
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0014_player_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='price',
        ),
        migrations.AddField(
            model_name='player',
            name='price_toBuy',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
