# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-28 06:04
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0016_auto_20181128_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_terminated',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
