# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-06 04:46
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0018_auto_20181129_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='experience',
        ),
        migrations.AddField(
            model_name='player',
            name='sudokoHobby',
            field=otree.db.models.StringField(choices=[('הרבה פעמים', 'הרבה פעמים'), ('לעתים קרובות', 'לעתים קרובות'), ('מדי פעם', 'מדי פעם'), ('באופן נדיר', 'באופן נדיר'), ('אף פעם לא', 'אף פעם לא')], max_length=10000, null=True, verbose_name='ג.\tהאם בעבר פתרת סודוקו כתחביב'),
        ),
        migrations.AddField(
            model_name='player',
            name='wordNumberHobby',
            field=otree.db.models.StringField(choices=[('הרבה פעמים', 'הרבה פעמים'), ('לעתים קרובות', 'לעתים קרובות'), ('מדי פעם', 'מדי פעם'), ('באופן נדיר', 'באופן נדיר'), ('אף פעם לא', 'אף פעם לא')], max_length=10000, null=True, verbose_name='ד.\tהאם בעבר פתרת משחקי אותיות או מספרים כתחביב'),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=otree.db.models.StringField(choices=[(' 18-19', ' 18-19'), (' 20-21', ' 20-21'), (' 22-23', ' 22-23'), ('24-25', '24-25'), ('26 ומעלה', '26 ומעלה')], max_length=10000, null=True, verbose_name='א.\tמהו גילך '),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=otree.db.models.StringField(choices=[('גבר', 'גבר'), ('אישה', 'אישה')], max_length=10000, null=True, verbose_name='ב.\tציין\\ח את מגדרך'),
        ),
        migrations.AlterField(
            model_name='player',
            name='seat_number',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='מספר המושב שלך:'),
        ),
    ]
