# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-10 00:32
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0020_remove_player_is_terminated'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='button_sequence',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='first_demo',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='first_demo_time',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='second_demo',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='second_demo_time',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
