# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-03 01:55
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0026_auto_20181227_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game_attemptted',
        ),
        migrations.AddField(
            model_name='player',
            name='game_attempted_seriously',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='games_looked_at',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
