# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-06 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0028_player_skip_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='seat_number',
        ),
    ]
