# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-25 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sudokusell_group', to='otree.Session')),
            ],
            options={
                'db_table': 'sudokusell_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('seat_number', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Your Seat Number:')),
                ('game_attemptted', otree.db.models.IntegerField(null=True)),
                ('game_correctted', otree.db.models.IntegerField(null=True)),
                ('price_toSell', otree.db.models.FloatField(null=True)),
                ('age', otree.db.models.StringField(choices=[('18-19', '18-19'), ('20-21', '20-21'), ('22-23', '22-23'), ('24-25', '24-25'), ('26 and older', '26 and older')], max_length=10000, null=True, verbose_name='How old are you')),
                ('gender', otree.db.models.StringField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10000, null=True, verbose_name='What is your gender?')),
                ('experience', otree.db.models.StringField(choices=[('very much', 'very much'), ('to a great degree', 'to a great degree'), ('in some  ocassions', 'in some  ocassions'), ('rarely or not at all', 'rarely or not at all')], max_length=10000, null=True, verbose_name='Do you practice “word puzzles” and “number puzzles” as a hobby,')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sudokusell.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sudokusell_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sudokusell_player', to='otree.Session')),
            ],
            options={
                'db_table': 'sudokusell_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sudokusell_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'sudokusell_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sudokusell.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sudokusell.Subsession'),
        ),
    ]
