# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-28 01:33
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sudokusell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_terminated',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='time_spend',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
