# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-05 12:48
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sudokusell', '0005_auto_20181205_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=otree.db.models.StringField(choices=[('גבר', 'גבר'), ('אישה', 'אישה')], max_length=10000, null=True, verbose_name='ב.\tציין\\ח את מגדרך    גבר \\ אישה'),
        ),
        migrations.AlterField(
            model_name='player',
            name='sudokoHobby',
            field=otree.db.models.StringField(choices=[('הרבה פעמים', 'הרבה פעמים'), ('לעתים קרובות', 'לעתים קרובות'), ('מדי פעם', 'מדי פעם'), ('rarely or not at all', 'rarely or not at all')], max_length=10000, null=True, verbose_name='ג.\tהאם בעבר פתרת סודוקו כתחביב ? '),
        ),
        migrations.AlterField(
            model_name='player',
            name='wordNumberHobby',
            field=otree.db.models.StringField(choices=[('very much', 'very much'), ('to a great degree', 'to a great degree'), ('in some  ocassions', 'in some  ocassions'), ('rarely or not at all', 'rarely or not at all')], max_length=10000, null=True, verbose_name='ד.\tהאם בעבר פתרת משחקי אותיות או מספרים כתחביב? '),
        ),
    ]
