# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-05 12:57
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sudokusell', '0011_auto_20181205_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=otree.db.models.StringField(choices=[('גבר', 'גבר'), ('אישה', 'אישה')], max_length=10000, null=True, verbose_name='ב.\tציין\\ח את מגדרך'),
        ),
    ]
