# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-06 01:41
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sudokusell', '0014_auto_20181206_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='seat_number',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
