# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-10 00:50
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sudokusell', '0018_auto_20181210_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='button_sequence',
        ),
        migrations.AddField(
            model_name='player',
            name='demo1_button_sequence',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='demo2_button_sequence',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
