# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-10 12:27
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sudokusell', '0019_auto_20181210_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='visit_other_websites',
            field=otree.db.models.StringField(default='No', max_length=10000, null=True),
        ),
    ]
