# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-03 02:40
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sudokusell', '0026_auto_20190103_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skip_time',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
